#!/bin/bash

[[ $# == 1 ]] && count=$1 || count=500

# Fetch some samples
samples=($(cat black.wav | xxd -cols 2 -g 2 -bits -s 44 -l $count -p))

echo read ${#samples[*]} samples

declare -A histogram

for s in ${samples[*]}; do
	histogram[$s]+=-
done

# Dump histogram
for key in ${!histogram[*]}; do
	echo -e $key\\t${histogram[$key]}\|
done
