#!/bin/bash

[[ $# == 1 ]] && count=$1 || count=750

# Fetch some samples
nibbles=8
readarray samples < <(xxd -cols $nibbles -plain -s 42 -len $(( nibbles * count )))

# Loop through samples
i=0
for s in ${samples[*]}; do

	# Extract left channel only
	s=${s:0:4}

	# Shift so all values are positive
	echo -e $i\\t$(( 16#$s + 16#ffff ))
	(( ++i ))
done | graph -T png > wav.png
