#!/bin/bash

[[ $# == 1 ]] && count=$1 || count=20

# Fetch some samples
nibbles=40
readarray samples < <(cat black.wav | xxd -cols $nibbles -p -l $(( nibbles * count )))

echo ${#samples[*]} samples

# Loop through samples
for s in ${samples[*]}; do
	s=${s:0:6}
	printf %x\\n $(( 16#$s ))
done
