#!/bin/bash

test='234abc234_ h___*&^    ello_élève ʘ‿ʘ'

function test_posix {
	class=$1
	echo -en $class\\t
	[[ $test =~ ${class}+ ]] && echo \"$BASH_REMATCH\" || echo no match
}

# alphabetic
test_posix '[[:alpha:]]'

# alphanumeric
test_posix '[[:alnum:]]'

# ASCII
test_posix '[[:ascii:]]'

# space and tab
test_posix '[[:blank:]]'

# space - all whitespace
test_posix '[[:space:]]'

# cntrl - control characters

# digit - digits
test_posix  '[[:digits:]]'

# xdigit - hexadecimal digits

# graph - anything except spaces and control characters
# lower - lowercase
# upper - uppdercase

# print - visible characters
# punct - punctuation and symbols
# word - letters, numbers and underscores
