#!/bin/bash

cat <<MIME
Content-Type: text/plain
Access-Control-Allow-Origin: *

MIME

# Check if an IP has been requested
if [[ $QUERY_STRING =~ [[:digit:]\.]{7,} ]]; then

	# Extract IP
	ip=$BASH_REMATCH

	# And ping it
	ping -c 1 -w 1 $ip >& /dev/null && echo 1 || echo 0
else
	# Otherwise report an error
	echo -1
fi
