#!/bin/bash

cat <<MIME
Content-Type: text/plain

MIME

function echo {
	printf \\n%s\\n "$*"
}

echo ARP table
ip neighbour

echo MAC address
ip n | while read line; do [[ $line =~ \ [[:xdigit:]:]{17}\  ]] && echo $BASH_REMATCH; done

echo Current IP
ip=$(hostname -I)

echo Current access point
iwgetid

echo Routing table
ip route

echo Visible access points
iwlist wlp1s0 scan  | grep ESSID

echo Portscan self
nc -vz $ip 1-10000 |& grep succeeded

# Resolve vendors
# Ping IPs on current network

echo Ping external IPs
ping -w 1 -c 1 8.8.8.8 && echo success || echo fail
