#!/bin/bash

cat <<MIME
Content-Type: text/plain

MIME

# Look up vendor from first half of MAC
function vendor {

	# If a MAC matches then look up the vendor
	if [[ $line =~ ([[:xdigit:]]{2}:){5}[[:xdigit:]]{2} ]]; then
		mac=$BASH_REMATCH
		echo -n $mac \-\ 

		# Strip colons
		mac=${mac//:/}

		# Look up MAC
		v=${mac:0:6}
		grep -i $v oui.txt || echo no match
	fi
}

# echo Current access point
# iwgetid

echo MAC addresses in ARP table
ip n | while read line; do

	vendor $line
done

# echo Current IP
# ip=$(hostname -I)

# echo Routing table
# ip route

echo Visible access points
# iwlist wlp1s0 scan  | grep -E 'ESSID|Address'
iwlist wlp1s0 scan | while read line; do
	
	vendor $line
done

# echo Portscan self
# nc -vz $ip 1-10000 |& grep succeeded

# Resolve vendors
# Ping IPs on current network

# echo Ping external IPs
# ping -w 1 -c 1 8.8.8.8 && echo success || echo fail
